// Export all routes for easy importing
export { default as authRoutes } from './auth.js';
export { default as userRoutes } from './users.js';
export { default as adminRoutes } from './admin.js';
export { default as courseRoutes } from './courses.js';
export { default as materialRoutes } from './materials.js';
export { default as enrollmentRoutes } from './enrollments.js';
export { default as googleOAuthRoutes } from './google-oauth.js';
export { default as assignmentRoutes } from './assignments.js';
export { default as gradeRoutes } from './grades.js';
export { default as searchRoutes } from './search.js';
export { default as notificationRoutes } from './notifications.js';
export { default as bugReportRoutes } from './bug-reports.js';
export { default as analyticsRoutes } from './analytics.js';
export { default as batchRoutes } from './batch.js';
export { default as twoFactorRoutes } from './twoFactor.js';
export { default as announcementRoutes } from './announcements.js';
export { default as invitationRoutes } from './invitations.js';
export { default as discussionRoutes } from './discussions.js';
